#include "segment_internal.h"

static double ulp(double x){double y=nextafter(x,INFINITY);return y-x;}
static ame_segment_status validate_ds(ame_segment*s,double *ds){if(!isfinite(*ds))return AME_SEGMENT_INVALID_ARGUMENT;double tol=64.0*ulp(fmax(1.0,fabs(s->L)));if(*ds < -tol || *ds > s->L+tol)return AME_SEGMENT_OUTSIDE_PREFIX;if(*ds<=0)*ds=0;else if(*ds>=s->L)*ds=s->L;return AME_SEGMENT_OK;}
static ame_segment_status map_status(cflow_status st){switch(st){case CFLOW_OK:return AME_SEGMENT_OK;case CFLOW_EVENT:case CFLOW_BEYOND_EVENT:case CFLOW_OUTSIDE_REAL_DOMAIN:return AME_SEGMENT_DOMAIN;case CFLOW_CONDITIONING_LIMIT:return AME_SEGMENT_CONDITIONING;default:return AME_SEGMENT_NUMERICAL_FAILURE;}}
static double state_rate(double x,double ds,double k0,double sigma){double q=fma(sigma,ds,k0),z=q*x;return 2*AME_MU_G*sqrt(fmax(0.0,fma(-z,z,1.0)));}
static int eta_selector(double x,double q,double b,double h){if(getenv("AME_ROBOT_DISABLE_REVERSE_ETA"))return 0;if(!(isfinite(x)&&isfinite(q)&&isfinite(b)&&isfinite(h)&&x>0&&h>0&&q!=0&&b!=0&&q*b<0))return 0;double qh=fma(b,h,q);if(q*qh<=0)return 0;double Q=fabs(q),Qh=fabs(qh),B=fabs(b),n=h*(Q+Qh)*(Q*Q+Qh*Qh)/(0.0985*B);if(!(isfinite(n)&&n>=3000))return 0;double z=Q*x;if(!(z>0&&z<1))return 0;double eta=sqrt((1-z)*(1+z))/z;return eta>0&&eta<=30&&isfinite(eta);}
static int eta_get(ame_segment*s,double ds,ame_reverse_eta_result*out){ame_grip_ws*g=&s->u.grip;if(!g->reverse_eta||g->boundary_start||!eta_selector(g->x0,s->k0,s->sigma,ds))return 0;if(g->has_eta_endpoint&&g->eta_endpoint_ds==ds){*out=g->eta_endpoint;return 1;}ame_reverse_eta_result r;if(!ame_reverse_eta_all(g->x0,s->k0,s->sigma,ds,1e-12,&r)||r.status!=AME_REVERSE_ETA_OK)return 0;const double *p=&r.x;for(int i=0;i<11;++i)if(!isfinite(p[i]))return 0;if(ds==s->L&&g->has_authoritative_w1&&fabs(AME_MU_G*r.x-g->authoritative_w1)>1e-8)return 0;if(ds==s->L){g->eta_endpoint=r;g->eta_endpoint_ds=ds;g->has_eta_endpoint=1;}*out=r;return 1;}
static double time_w0(ame_segment*s,double raw,double reg,ame_segment_status *st){ame_grip_ws*g=&s->u.grip;if(g->boundary_start)return 0;if(s->w0!=0)return raw*AME_INV_MU_G_SQRT_MU_G;if(g->time_w0_policy==AME_TIME_W0_RAISE){*st=AME_SEGMENT_NUMERICAL_FAILURE;return NAN;}if(g->time_w0_policy==AME_TIME_W0_RENORMALIZED)return reg*AME_INV_MU_G_SQRT_MU_G;return -INFINITY;}

static double boundary_next_event(double x0,double q0,double b,double h){if(h<=0)return NAN;double scale=b!=0?fabs(q0/b):h,eps=fmin(h*1e-8,scale*1e-8);if(!(eps>0))eps=nextafter(0.0,1.0);if(eps>=h)return NAN;cflow_eval_result r;cflow_boundary_eval(x0,q0,b,eps,&r);if(r.status!=CFLOW_OK)return NAN;double q1=fma(b,eps,q0);cflow_event_result ev;cflow_first_event(r.x,q1,b,h-eps,&ev);if((ev.status==CFLOW_EVENT||ev.status==CFLOW_CONDITIONING_LIMIT)&&isfinite(ev.time))return eps+ev.time;return NAN;}

ame_segment_status ame_grip_init(ame_segment*s,const ame_segment_options*o){if(!ame_finite4(s->L,s->sigma,s->w0,s->k0)||s->L<0||s->w0<0)return AME_SEGMENT_INVALID_ARGUMENT;ame_grip_ws*g=&s->u.grip;memset(g,0,sizeof(*g));g->boundary_start=o?!!o->boundary_start:0;g->time_w0_policy=o?o->time_w0_policy:AME_TIME_W0_NEGATIVE_INFINITY;g->reverse_eta=o?!!o->reverse_eta:0;g->has_authoritative_w1=o?!!o->has_authoritative_w1:0;g->authoritative_w1=o?o->authoritative_w1:0;double x0=s->w0*AME_MU_G_INV,z0=s->k0*x0,margin=fma(-z0,z0,1.0);if(g->boundary_start){if(s->k0==0||s->sigma==0||!(s->sigma/s->k0<0))return AME_SEGMENT_INVALID_ARGUMENT;double expected=AME_MU_G/fabs(s->k0),mx=fmax(fmax(expected,fabs(s->w0)),1.0),tol=64*ulp(mx);if(fabs(s->w0-expected)>tol)return AME_SEGMENT_INVALID_ARGUMENT;s->w0=expected;x0=s->w0*AME_MU_G_INV;}else if(!(margin>0))return AME_SEGMENT_DOMAIN;g->x0=x0;g->anchors=g->inline_anchors;g->cap_anchors=64;g->n_anchors=1;g->anchors[0].s=0;g->anchors[0].x=x0;return AME_SEGMENT_OK;}
void ame_grip_destroy(ame_segment*s){ame_grip_ws*g=&s->u.grip;if(g->anchors&&g->anchors!=g->inline_anchors)free(g->anchors);g->anchors=NULL;}
static size_t upper_anchor(ame_grip_ws*g,double ds){
    if(g->n_anchors&&ds>=g->anchors[g->n_anchors-1].s)return g->n_anchors;
    size_t lo=0,hi=g->n_anchors;
    while(lo<hi){size_t m=lo+(hi-lo)/2;if(g->anchors[m].s<=ds)lo=m+1;else hi=m;}
    return lo;
}
static int insert_anchor(ame_grip_ws*g,size_t pos,double s,double x){if(g->n_anchors==g->cap_anchors){size_t nc=g->cap_anchors*2;ame_grip_anchor*p=malloc(nc*sizeof(*p));if(!p)return 0;memcpy(p,g->anchors,g->n_anchors*sizeof(*p));if(g->anchors!=g->inline_anchors)free(g->anchors);g->anchors=p;g->cap_anchors=nc;}memmove(&g->anchors[pos+1],&g->anchors[pos],(g->n_anchors-pos)*sizeof(*g->anchors));g->anchors[pos]=(ame_grip_anchor){s,x};g->n_anchors++;return 1;}
static ame_segment_status eval_anchor(ame_segment*s,double ds,double*x,cflow_status*status,double*event){ame_grip_ws*g=&s->u.grip;size_t up=upper_anchor(g,ds),i=up-1;double si=g->anchors[i].s,xi=g->anchors[i].x;if(si==ds){g->cache_hits++;*x=xi;*status=CFLOW_OK;*event=NAN;return AME_SEGMENT_OK;}double d=ds-si,qi=fma(s->sigma,si,s->k0);cflow_eval_result r;if(g->boundary_start&&si==0)cflow_boundary_eval(xi,qi,s->sigma,d,&r);else cflow_eval(xi,qi,s->sigma,d,&r);g->cflow_calls++;g->local_steps+=r.steps;*x=r.x;*status=r.status;*event=isfinite(r.event_time)?si+r.event_time:NAN;if(r.status==CFLOW_OK&&!insert_anchor(g,up,ds,r.x))return AME_SEGMENT_ALLOCATION_FAILURE;return AME_SEGMENT_OK;}

ame_segment_status ame_grip_w(ame_segment*s,double ds,double*out){ame_segment_status st=validate_ds(s,&ds);if(st)return st;ame_grip_ws*g=&s->u.grip;if(ds==0){if(!s->grad)g->cache_hits++;*out=s->w0;return AME_SEGMENT_OK;}if(s->grad){if(ds==s->L&&g->has_endpoint_value){*out=g->endpoint_value;return AME_SEGMENT_OK;}cflow_eval_result r;if(g->boundary_start)cflow_boundary_eval(g->x0,s->k0,s->sigma,ds,&r);else cflow_eval(g->x0,s->k0,s->sigma,ds,&r);if(r.status!=CFLOW_OK&&r.status!=CFLOW_EVENT)return map_status(r.status);*out=AME_MU_G*r.x;if(ds==s->L&&r.status==CFLOW_OK){g->has_endpoint_value=1;g->endpoint_value=*out;}return AME_SEGMENT_OK;}double x,ev;cflow_status cs;st=eval_anchor(s,ds,&x,&cs,&ev);if(st)return st;if(cs!=CFLOW_OK&&cs!=CFLOW_EVENT)return map_status(cs);*out=AME_MU_G*x;return AME_SEGMENT_OK;}
ame_segment_status ame_grip_time(ame_segment*s,double ds,double*out){ame_segment_status st=validate_ds(s,&ds);if(st)return st;if(ds==0){*out=0;return AME_SEGMENT_OK;}ame_grip_ws*g=&s->u.grip;cflow_integral_value_result r;if(g->boundary_start)cflow_boundary_integral_value(g->x0,s->k0,s->sigma,ds,&r);else cflow_integral_value(g->x0,s->k0,s->sigma,ds,&r);if(r.status!=CFLOW_OK&&r.status!=CFLOW_EVENT)return map_status(r.status);*out=AME_INV_SQRT_MU_G*r.integral;return AME_SEGMENT_OK;}
static ame_segment_status fill_all_from_cflow(ame_segment*s,const cflow_all_result*r,double ds,ame_segment_all_jac*out){ame_segment_status st=AME_SEGMENT_OK;double tw=time_w0(s,r->dI_dx0,r->regularized_dI_dx0,&st);if(st)return st;out->w=AME_MU_G*r->x;out->state_jac[0]=AME_MU_G*r->dx_dh;out->state_jac[1]=AME_MU_G*r->dx_db;out->state_jac[2]=r->dx_dx0;out->state_jac[3]=AME_MU_G*r->dx_dq0;out->state_jac[4]=s->sigma;out->state_jac[5]=ds;out->state_jac[6]=0;out->state_jac[7]=1;out->time=r->integral*AME_INV_SQRT_MU_G;out->time_jac[0]=r->dI_dh*AME_INV_SQRT_MU_G;out->time_jac[1]=r->dI_db*AME_INV_SQRT_MU_G;out->time_jac[2]=tw;out->time_jac[3]=r->dI_dq0*AME_INV_SQRT_MU_G;return AME_SEGMENT_OK;}
static ame_segment_status fill_all_from_eta(ame_segment*s,const ame_reverse_eta_result*r,double ds,ame_segment_all_jac*out){ame_segment_status st=AME_SEGMENT_OK;double tw=time_w0(s,r->dI_dx0,r->regularized_dI_dx0,&st);if(st)return st;out->w=AME_MU_G*r->x;out->state_jac[0]=AME_MU_G*r->dx_dh;out->state_jac[1]=AME_MU_G*r->dx_db;out->state_jac[2]=r->dx_dx0;out->state_jac[3]=AME_MU_G*r->dx_dq0;out->state_jac[4]=s->sigma;out->state_jac[5]=ds;out->state_jac[6]=0;out->state_jac[7]=1;out->time=r->integral*AME_INV_SQRT_MU_G;out->time_jac[0]=r->dI_dh*AME_INV_SQRT_MU_G;out->time_jac[1]=r->dI_db*AME_INV_SQRT_MU_G;out->time_jac[2]=tw;out->time_jac[3]=r->dI_dq0*AME_INV_SQRT_MU_G;return AME_SEGMENT_OK;}
static ame_segment_status full_endpoint(ame_segment*s,ame_segment_all_jac*out){ame_grip_ws*g=&s->u.grip;if(g->has_endpoint_all){*out=g->endpoint_all;return AME_SEGMENT_OK;}ame_reverse_eta_result er;if(eta_get(s,s->L,&er)){ame_segment_status st=fill_all_from_eta(s,&er,s->L,out);if(st)return st;}else{cflow_all_result r;if(g->boundary_start)cflow_boundary_eval_all(g->x0,s->k0,s->sigma,s->L,&r);else cflow_eval_all(g->x0,s->k0,s->sigma,s->L,&r);if(r.status!=CFLOW_OK)return map_status(r.status);ame_segment_status st=fill_all_from_cflow(s,&r,s->L,out);if(st)return st;}g->endpoint_all=*out;g->has_endpoint_all=1;g->endpoint_value=out->w;g->has_endpoint_value=1;return AME_SEGMENT_OK;}
ame_segment_status ame_grip_wjac(ame_segment*s,double ds,ame_segment_state_jac*out){if(!s->grad)return AME_SEGMENT_UNSUPPORTED;ame_segment_status st=validate_ds(s,&ds);if(st)return st;ame_grip_ws*g=&s->u.grip;if(ds==0){out->w=s->w0;out->jac[0]=state_rate(g->x0,0,s->k0,s->sigma);out->jac[1]=0;out->jac[2]=1;out->jac[3]=0;out->jac[4]=s->sigma;out->jac[5]=0;out->jac[6]=0;out->jac[7]=1;return AME_SEGMENT_OK;}if(ds==s->L){ame_segment_all_jac a;st=full_endpoint(s,&a);if(st)return st;out->w=a.w;memcpy(out->jac,a.state_jac,sizeof(out->jac));return AME_SEGMENT_OK;}cflow_eval_jac_result r;if(g->boundary_start)cflow_boundary_eval_jacobian(g->x0,s->k0,s->sigma,ds,&r);else cflow_eval_jacobian(g->x0,s->k0,s->sigma,ds,&r);if(r.status!=CFLOW_OK)return map_status(r.status);out->w=AME_MU_G*r.x;out->jac[0]=AME_MU_G*r.dx_dh;out->jac[1]=AME_MU_G*r.dx_db;out->jac[2]=r.dx_dx0;out->jac[3]=AME_MU_G*r.dx_dq0;out->jac[4]=s->sigma;out->jac[5]=ds;out->jac[6]=0;out->jac[7]=1;return AME_SEGMENT_OK;}
ame_segment_status ame_grip_tjac(ame_segment*s,double ds,ame_segment_time_jac*out){if(!s->grad)return AME_SEGMENT_UNSUPPORTED;ame_segment_status st=validate_ds(s,&ds);if(st)return st;ame_grip_ws*g=&s->u.grip;if(ds==0){out->time=0;out->jac[0]=s->w0==0?INFINITY:1/sqrt(s->w0);out->jac[1]=out->jac[2]=out->jac[3]=0;return AME_SEGMENT_OK;}if(ds==s->L){ame_segment_all_jac a;st=full_endpoint(s,&a);if(st)return st;out->time=a.time;memcpy(out->jac,a.time_jac,sizeof(out->jac));return AME_SEGMENT_OK;}ame_reverse_eta_result er;if(eta_get(s,ds,&er)){ame_segment_all_jac a;st=fill_all_from_eta(s,&er,ds,&a);if(st)return st;out->time=a.time;memcpy(out->jac,a.time_jac,sizeof(out->jac));return AME_SEGMENT_OK;}cflow_integral_jac_result r;if(g->boundary_start)cflow_boundary_integral_jacobian(g->x0,s->k0,s->sigma,ds,&r);else cflow_integral_jacobian(g->x0,s->k0,s->sigma,ds,&r);if(r.status!=CFLOW_OK)return map_status(r.status);out->time=r.integral*AME_INV_SQRT_MU_G;out->jac[0]=r.dI_dh*AME_INV_SQRT_MU_G;out->jac[1]=r.dI_db*AME_INV_SQRT_MU_G;out->jac[2]=time_w0(s,r.dI_dx0,r.regularized_dI_dx0,&st);out->jac[3]=r.dI_dq0*AME_INV_SQRT_MU_G;return st;}
ame_segment_status ame_grip_all(ame_segment*s,double ds,ame_segment_all_jac*out){if(!s->grad)return AME_SEGMENT_UNSUPPORTED;ame_segment_status st=validate_ds(s,&ds);if(st)return st;ame_grip_ws*g=&s->u.grip;if(ds==0){out->w=s->w0;out->state_jac[0]=state_rate(g->x0,0,s->k0,s->sigma);out->state_jac[1]=0;out->state_jac[2]=1;out->state_jac[3]=0;out->state_jac[4]=s->sigma;out->state_jac[5]=0;out->state_jac[6]=0;out->state_jac[7]=1;out->time=0;out->time_jac[0]=s->w0==0?INFINITY:1/sqrt(s->w0);out->time_jac[1]=out->time_jac[2]=out->time_jac[3]=0;return AME_SEGMENT_OK;}if(ds==s->L)return full_endpoint(s,out);cflow_all_result r;if(g->boundary_start)cflow_boundary_eval_all(g->x0,s->k0,s->sigma,ds,&r);else cflow_eval_all(g->x0,s->k0,s->sigma,ds,&r);if(r.status!=CFLOW_OK)return map_status(r.status);return fill_all_from_cflow(s,&r,ds,out);}
ame_segment_status ame_grip_probe(ame_segment*s,double ds,ame_segment_domain_probe*out){ame_segment_status st=validate_ds(s,&ds);if(st)return st;ame_grip_ws*g=&s->u.grip;if(ds==0){out->pre_event=1;out->event_position=NAN;out->cflow_status=CFLOW_OK;return AME_SEGMENT_OK;}cflow_eval_result r;if(g->boundary_start)cflow_boundary_eval(g->x0,s->k0,s->sigma,ds,&r);else cflow_eval(g->x0,s->k0,s->sigma,ds,&r);if(r.status==CFLOW_OK){out->pre_event=1;out->event_position=NAN;out->cflow_status=CFLOW_OK;return AME_SEGMENT_OK;}if(r.status==CFLOW_EVENT){out->pre_event=0;out->event_position=isfinite(r.event_time)?r.event_time:ds;out->cflow_status=r.status;return AME_SEGMENT_OK;}if(r.status==CFLOW_BEYOND_EVENT){out->pre_event=0;out->event_position=isfinite(r.event_time)?r.event_time:NAN;out->cflow_status=r.status;return AME_SEGMENT_OK;}if(g->boundary_start&&r.status==CFLOW_NUMERICAL_FAILURE){double ev=boundary_next_event(g->x0,s->k0,s->sigma,ds);if(isfinite(ev)){out->pre_event=0;out->event_position=ev;out->cflow_status=CFLOW_BEYOND_EVENT;return AME_SEGMENT_OK;}}return map_status(r.status);}
ame_segment_status ame_grip_cross_state(ame_segment*s,double ds,ame_segment_crossing_state*out){
    if(!out)return AME_SEGMENT_INVALID_ARGUMENT;
    ame_segment_status st=validate_ds(s,&ds);if(st)return st;
    ame_grip_ws*g=&s->u.grip;
    double w=NAN,ev=NAN; cflow_status cs=CFLOW_OK;
    if(ds==0.0){
        if(!s->grad)g->cache_hits++;
        w=s->w0;
    }else if(!s->grad){
        double x=NAN;
        st=eval_anchor(s,ds,&x,&cs,&ev);if(st)return st;
        if(cs==CFLOW_OK||cs==CFLOW_EVENT)w=AME_MU_G*x;
        else if(cs==CFLOW_BEYOND_EVENT||cs==CFLOW_OUTSIDE_REAL_DOMAIN){
            out->w=NAN; out->k=fma(s->sigma,ds,s->k0); out->q=NAN; out->g2=-INFINITY;
            out->outside_domain=1; out->event_position=ev; out->cflow_status=(int)cs;
            return AME_SEGMENT_OK;
        }else return map_status(cs);
    }else{
        cflow_eval_result r;
        if(g->boundary_start)cflow_boundary_eval(g->x0,s->k0,s->sigma,ds,&r);else cflow_eval(g->x0,s->k0,s->sigma,ds,&r);
        cs=r.status; ev=isfinite(r.event_time)?r.event_time:NAN;
        if(cs==CFLOW_OK||cs==CFLOW_EVENT)w=AME_MU_G*r.x;
        else if(cs==CFLOW_BEYOND_EVENT||cs==CFLOW_OUTSIDE_REAL_DOMAIN){
            out->w=NAN; out->k=fma(s->sigma,ds,s->k0); out->q=NAN; out->g2=-INFINITY;
            out->outside_domain=1; out->event_position=ev; out->cflow_status=(int)cs;
            return AME_SEGMENT_OK;
        }else return map_status(cs);
    }
    double k=fma(s->sigma,ds,s->k0),q=w*k,g2=fma(-q,q,AME_MU_G*AME_MU_G);
    out->w=w;out->k=k;out->q=q;out->g2=g2;out->outside_domain=0;
    out->event_position=ev;out->cflow_status=(int)cs;
    return AME_SEGMENT_OK;
}

ame_segment_status ame_grip_renorm(ame_segment*s,double ds,double*out){if(!s->grad)return AME_SEGMENT_UNSUPPORTED;ame_segment_status st=validate_ds(s,&ds);if(st)return st;ame_grip_ws*g=&s->u.grip;if(ds==0||g->boundary_start){*out=0;return AME_SEGMENT_OK;}ame_reverse_eta_result er;if(eta_get(s,ds,&er)){*out=er.regularized_dI_dx0*AME_INV_MU_G_SQRT_MU_G;return AME_SEGMENT_OK;}cflow_integral_jac_result r;cflow_integral_jacobian(g->x0,s->k0,s->sigma,ds,&r);if(r.status!=CFLOW_OK)return map_status(r.status);*out=r.regularized_dI_dx0*AME_INV_MU_G_SQRT_MU_G;return AME_SEGMENT_OK;}
