"""Production clothoid path optimization.

The package separates three layers:

* geometry, speed-profile, and exact-gradient kernels,
* backend-neutral corridor constraint generation and separation, and
* the optimizer orchestration in :mod:`.path_optimizer`.

SciPy is imported lazily only when the SLSQP backend is invoked.
"""

from __future__ import annotations

from . import (
    constraint_generation,
    crossings,
    geometry,
    geometry_gradients,
    kkt_lsq,
    knot_parameterization,
    phase_one_handoff,
    path_optimizer,
    reverse_solver,
    scalar_reverse_solver,
    sparse_sqp,
    adaptive_sparse_polish,
    sparse_sqp_continuation,
    sqp_supervisor,
    total_gradients,
)

from .geometry import CircularArc, EulerSpiral, Geometry, Line, create_geo, fresnel
from .geometry_gradients import (
    GeometryPath,
    GeometryState,
    MomentResult,
    clothoid_moments,
    compile_geometry_path,
    knot_parameters_to_raw,
    pullback_raw_gradient_to_knot_parameters,
    pullback_raw_gradient_to_knots,
)
from .scalar_reverse_solver import (
    ScalarTimeDiagnostics,
    evaluate_time_scalar,
    evaluate_time_scalar_result,
)
from .reverse_solver import (
    AnchorInsertionStats,
    AnchorWitness,
    EventKind,
    InternalCapAnchor,
    FRICTION_DOMAIN_MARGIN,
    INTERNAL_CAP_G2_MARGIN,
    FRICTION_DOMAIN_SCAN,
    PassKind,
    PhaseProfiler,
    ProdSpeedProfileBuild,
    build_has_mode_event,
    build_scalar_speed_profile,
    candidate_coverage_witnesses,
    collect_internal_cap_anchors,
    envelope_continuity_witnesses,
    event_counts,
    friction_domain_ok,
    friction_g2,
    prepare_reverse_build,
    prepare_reverse_time_build,
    reverse_time_objective,
    reverse_backend,
    set_reverse_backend,
    using_reverse_backend,
    time_value_and_gradient,
)
from .total_gradients import (
    EndpointObjective,
    GeometryObjective,
    TotalGradientResult,
    curvature_energy_value_and_gradient,
    curvature_energy_value_and_raw_gradient,
    linear_endpoint_objective,
    path_length_value_and_raw_gradient,
    quadratic_endpoint_target,
    total_knot_value_and_gradient,
)
from .knot_parameterization import KnotCoordinateSettings, LogLengthKnotMap
from .phase_one_handoff import (
    CanonicalHandoffState,
    EndpointBranchAlignment,
    HandoffCanonicalizationSettings,
    align_endpoint_target_to_path,
    canonical_angle,
    canonicalize_phase_one_handoff,
)
from .adaptive_sparse_polish import (
    AdaptiveBatchRecord,
    AdaptiveBatchSettings,
    AdaptivePolishResult,
    AdaptiveSafeCheckpoint,
    CutProvenance,
    RestorationAttempt,
    RestorationRecord,
    SupervisedAdaptivePolishResult,
    run_adaptive_sparse_polish,
    run_supervised_adaptive_sparse_polish,
)
from .sparse_sqp import (
    ObjectiveEvaluationTimeout,
    SparseSQPContinuationState,
    SparseSQPDiagnosticControls,
    SparseSQPIteration,
    SparseSQPResult,
    SparseSQPSettings,
    SparseSQPStageTelemetry,
    solve_sparse_filter_sqp,
)
from .phase_one_supervisor import (
    PhaseOneDiagnosticCheckpoint,
    SupervisedPhaseOneResult,
    run_supervised_phase_one,
)
from .sqp_supervisor_service import (
    ExternalSupervisorServiceClient,
    SupervisorServiceClientSettings,
)
from .sqp_supervisor import (
    FailureReason,
    SupervisedBatchOutcome,
    SupervisedBatchRunner,
    SupervisorSettings,
    WorkerContext,
)
from .kkt_lsq import (
    BoxBounds,
    KKTReport,
    MixedLeastSquaresResult,
    estimate_kkt_residual,
    solve_mixed_least_squares,
)
from .constraint_generation import (
    BodyCorner,
    CombinedConstraintOracle,
    ConstraintFamily,
    ConstraintPool,
    CurvatureSlopeConstraint,
    ConvexCell,
    CorridorModel,
    EndpointBoxConstraint,
    EndpointPoseEquality,
    HalfSpace,
    KnotGeometryCache,
    PointConstraint,
    PoseJacobian,
    RectangleBody,
    RectangleConstraintOracle,
    ScalarObjective,
    SeparationMaximum,
    SeparationReport,
    SeparationSettings,
    StackedVectorConstraint,
    VectorConstraint,
    WallSeparation,
    add_report_violations,
    separate_compiled_path,
    separate_rectangle_path,
    stack_vector_constraints,
)
from .path_optimizer import (
    CachedObjective,
    ExchangeResult,
    ExchangeRoundResult,
    ExchangeSettings,
    FiniteSolveResult,
    NonlinearSolveResult,
    PathOptimizationResult,
    PathOptimizerSettings,
    PhaseOneResult,
    PhaseOneSettings,
    SLSQPSettings,
    ScalingSettings,
    SolveScaling,
    optimize_path,
    project_path_to_feasibility,
    run_constraint_generation,
    run_phase_one,
    solve_finite_slsqp,
    solve_finite_sparse_sqp,
    solve_finite_nlp,
    stabilize_phase_one_sparse_exchange,
)

__all__ = [
    # Submodules.
    "constraint_generation",
    "crossings",
    "geometry",
    "geometry_gradients",
    "kkt_lsq",
    "knot_parameterization",
    "phase_one_handoff",
    "path_optimizer",
    "reverse_solver",
    "scalar_reverse_solver",
    "sparse_sqp",
    "sparse_sqp_continuation",
    "sqp_supervisor",
    "total_gradients",
    # Geometry.
    "Geometry",
    "Line",
    "CircularArc",
    "EulerSpiral",
    "create_geo",
    "fresnel",
    "GeometryPath",
    "GeometryState",
    "MomentResult",
    "clothoid_moments",
    "compile_geometry_path",
    "knot_parameters_to_raw",
    "pullback_raw_gradient_to_knot_parameters",
    "pullback_raw_gradient_to_knots",
    # Scalar speed/time evaluation.
    "ScalarTimeDiagnostics",
    "evaluate_time_scalar",
    "evaluate_time_scalar_result",
    # Speed/time gradients.
    "EventKind",
    "InternalCapAnchor",
    "AnchorWitness",
    "AnchorInsertionStats",
    "PassKind",
    "PhaseProfiler",
    "ProdSpeedProfileBuild",
    "FRICTION_DOMAIN_MARGIN",
    "INTERNAL_CAP_G2_MARGIN",
    "FRICTION_DOMAIN_SCAN",
    "friction_g2",
    "friction_domain_ok",
    "build_scalar_speed_profile",
    "collect_internal_cap_anchors",
    "candidate_coverage_witnesses",
    "envelope_continuity_witnesses",
    "prepare_reverse_build",
    "prepare_reverse_time_build",
    "reverse_time_objective",
    "time_value_and_gradient",
    "reverse_backend",
    "set_reverse_backend",
    "using_reverse_backend",
    "event_counts",
    "build_has_mode_event",
    "EndpointObjective",
    "GeometryObjective",
    "TotalGradientResult",
    "curvature_energy_value_and_gradient",
    "curvature_energy_value_and_raw_gradient",
    "linear_endpoint_objective",
    "path_length_value_and_raw_gradient",
    "quadratic_endpoint_target",
    "total_knot_value_and_gradient",
    # Constraint generation.
    "ScalarObjective",
    "VectorConstraint",
    "HalfSpace",
    "ConvexCell",
    "BodyCorner",
    "RectangleBody",
    "CorridorModel",
    "ConstraintFamily",
    "PointConstraint",
    "ConstraintPool",
    "CurvatureSlopeConstraint",
    "PoseJacobian",
    "KnotGeometryCache",
    "RectangleConstraintOracle",
    "EndpointBoxConstraint",
    "EndpointPoseEquality",
    "CombinedConstraintOracle",
    "StackedVectorConstraint",
    "stack_vector_constraints",
    "SeparationMaximum",
    "WallSeparation",
    "SeparationReport",
    "SeparationSettings",
    "separate_compiled_path",
    "separate_rectangle_path",
    "add_report_violations",
    # KKT diagnostics.
    "BoxBounds",
    "KKTReport",
    "MixedLeastSquaresResult",
    "estimate_kkt_residual",
    "solve_mixed_least_squares",
    # Knot optimizer coordinates.
    "KnotCoordinateSettings",
    "LogLengthKnotMap",
    "CanonicalHandoffState",
    "EndpointBranchAlignment",
    "HandoffCanonicalizationSettings",
    "align_endpoint_target_to_path",
    "canonical_angle",
    "canonicalize_phase_one_handoff",
    # Sparse filter-SQP prototype.
    "ObjectiveEvaluationTimeout",
    "SparseSQPContinuationState",
    "SparseSQPDiagnosticControls",
    "SparseSQPIteration",
    "SparseSQPResult",
    "SparseSQPSettings",
    "SparseSQPStageTelemetry",
    "solve_sparse_filter_sqp",
    "AdaptiveBatchRecord",
    "AdaptiveBatchSettings",
    "AdaptiveSafeCheckpoint",
    "AdaptivePolishResult",
    "CutProvenance",
    "SupervisedAdaptivePolishResult",
    "RestorationAttempt",
    "RestorationRecord",
    "run_supervised_adaptive_sparse_polish",
    "run_adaptive_sparse_polish",
    # Supervised execution.
    "FailureReason",
    "SupervisedBatchOutcome",
    "SupervisedBatchRunner",
    "PhaseOneDiagnosticCheckpoint",
    "SupervisedPhaseOneResult",
    "run_supervised_phase_one",
    "SupervisorSettings",
    "ExternalSupervisorServiceClient",
    "SupervisorServiceClientSettings",
    "WorkerContext",
    # Optimizer orchestration.
    "ScalingSettings",
    "SLSQPSettings",
    "SolveScaling",
    "NonlinearSolveResult",
    "FiniteSolveResult",
    "ExchangeSettings",
    "ExchangeRoundResult",
    "ExchangeResult",
    "PhaseOneSettings",
    "PhaseOneResult",
    "CachedObjective",
    "PathOptimizerSettings",
    "PathOptimizationResult",
    "solve_finite_slsqp",
    "solve_finite_sparse_sqp",
    "solve_finite_nlp",
    "stabilize_phase_one_sparse_exchange",
    "run_constraint_generation",
    "run_phase_one",
    "optimize_path",
    "project_path_to_feasibility",
]
